from db.models.chat_message import ChatMessage
from sqlalchemy.orm import Session


class ChatDB:
    def __init__(self, db_session: Session, user_id=None):
        self.db_session = db_session
        self.user_id = user_id

    def get_messages(self, session_id):
        messages = self.db_session.query(ChatMessage)\
            .filter(ChatMessage.session_id == session_id)\
            .order_by(ChatMessage.created_at)\
            .all()
        return [{"role": m.role, "content": m.content} for m in messages]

    def save_message(self, session_id, role, content):
        message = ChatMessage(
            # id will be autogenerated.
            session_id=session_id,
            role=role,
            content=content,
            user_id=self.user_id
        )
        self.db_session.add(message)
        self.db_session.commit()
